connective-health/public-docs

product/structured-reports.mdx
=> PS-676: Add Product Content

product/webhooks.mdx
Also tidy up an awkward sentence.
=> PS-1037: Add Batch ID to Webhook Content 

patient-appointment-api.yml
* Document patient categories
* Dosage amount & strength no longer required
* Misc minor updates
=> PS-1040, PS-955: Disease specific processing, Med Request API update

clinical-data-sharing/encounter-summary.mdx, mint.json, patient-appointment-api.yml
* adding encounter summary to public API
=> PS-980: Encounter Summary

clinical-data-sharing/patient-record.mdx, mint.json, patient-appointment-api.yml
- Clinical notes updates
- Standardized language across requests
- HTTP 403 Forbidden responses 
- Some structural updates based on latest OpenApi build
=> PS-1062: Create post-visit sharing API

patient-appointment-api.yml
* added `medicalSummaryPeriod`
=> PS-1155: Dates of Service Filter

patient-appointment-api.yml
=> PS-1168: Bariatric template V1

patient-appointment-api.yml
* initial API for submitting a panel of patients
=> PS-913: Med History API

patient-appointment-api.yml
* add category
* bump API minor version
=> PS-1222: Womens health template v1

patient-appointment-api.yml
* add category
* bump API minor version
=> PS-1235: Disease template: Oncological

patient-appointment-api.yml
* add categories for both
* bump API minor version
=> PS-1261, PS-1262: Disease templates: Dermatological, Gastroenterological

patient-appointment-api.yml
* bump API minor version (even though this technically is breaking change, the feature is in beta)
=> PS-1254: Allow for multiple encounter.diagnosis elements on the Encounter Summary API

patient-appointment-api.yml
* Dental, Men's Health, Otolaryngological, Renal, Urological
=> PS-1284, PS-1286, PS-1290, PS-1325, PS-1326: Five new disease templates

patient-appointment-api.yml
* Autoimmune
* General Surgery
* Lymphatic
* Toxicological
=> PS-1506, PS-1507, PS-1508, PS-1509: New Disease Templates

implementation/api-integration.mdx
* added links from integration site to other pages to make information more clear
* added URLs to the documentation site
=> PS-1502: Minor Documentation Fixes

implementation/api-integration.mdx, mint.json, product/webhooks.mdx, responses/cloud-storage.mdx, responses/ehr-integration.mdx
* added new EHR integration page
* bit more cleanup and improvements to other request and response pages
=> PS-1466: EHR API Integration

api-reference/patient-data-v2-upgrade-guide.mdx, api-reference/release-notes.mdx, clinical-data/patient-data-processing-v1.mdx, clinical-data/patient-data-v2.mdx, mint.json, patient-appointment-api.yml
* new documentation for patient data endpoint
* upgrade guide
* release notes page
=> PS-1599: New Patient Data Endpoint

api-reference/release-notes.mdx, patient-appointment-api.yml
* improve documentation around medications of interest
* fixed issue where Directives V2 weren't being used by the API
=> PS-1500: Medications of interest

patient-appointment-api.yml
* fixed the panel response to be the correct class
=> PS-1600: Fix Panel Response

api-reference/release-notes.mdx, clinical-data/patient-data-v2-validate.mdx, mint.json, patient-appointment-api.yml
* document for v3.1.0 regarding new validate only endpoint
=> PS-1769: Validation Endpoint

api-reference/patient-data-v2-upgrade-guide.mdx, api-reference/release-notes.mdx, patient-appointment-api.yml
* updates to include validating that certain top level arrays cannot be null
* updated release notes
* removed warning about API in active development
=> PS-1848: Validation Updates

api-reference/release-notes.mdx, patient-appointment-api.yml
* documentation updates for KAID configuration details
=> PS-1873: KAID Configuration

api-reference/release-notes.mdx, patient-appointment-api.yml
* enforce maximum number of patient addresses
=> PS-1643: Patient Max Addresses

responses/cloud-storage.mdx
* Added `providerNpi` value to list of configurable file path template options.
=> PS-1995: Added the ProviderNpi value to configurable file path template
